MCFC/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mcfcapp.urls')),



]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


   

mcfcapp/urls.py
from mcfcapp.views import *
from django.urls import include, path
from mcfcapp import views
from django.conf import settings

app_name = "mcfcapp"
urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('member/', ClientMemberView.as_view(), name='clientmember'),
    path('event/', ClientEventView.as_view(), name='clientevent'),
    path('gallery/', ClientGalleryView.as_view(), name='clientgallery'),

]

mcfcapp/models.py
from django.db import models

# Create your models here.

mcfcapp/views.py
from django.shortcuts import render
from django.views.generic import *
from django.views.generic.edit import *


class ClientHomeView(TemplateView):
    template_name = 'clienttemplates/clienthomepage.html'


class ClientMemberView(TemplateView):
    template_name = 'clienttemplates/clientmemberpage.html'


class ClientEventView(TemplateView):
    template_name = 'clienttemplates/clienteventpage.html'


class ClientGalleryView(TemplateView):
    template_name = 'clienttemplates/clientgallerypage.html'

templates/clienttemplates/clientbasepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en-AU" data-whatinput="mouse" data-whatintent="mouse">
<head>
  <title>MCFCN</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://use.fontawesome.com/45a5a1da21.js"></script>
  <link
  rel="stylesheet"
  id="easy_load_more-frontend-css"
  href="{% static 'clientstatic/homepage/css/frontend.css' %}"
  type="text/css"
  media="all"
  />
  <link
  rel="stylesheet"
  id="dpsp-frontend-style-css"
  href="{% static 'clientstatic/homepage/css/style-frontend.css' %}"
  type="text/css"
  media="all"
  />
  <link
  rel="stylesheet"
  id="main-stylesheet-css"
  href="{% static 'clientstatic/homepage/css/app.css' %}"
  type="text/css"
  media="all"
  />
  <link
  rel="stylesheet"
  id="wpmtst-custom-style-css"
  href="{% static 'clientstatic/homepage/css/custom.css' %}"
  type="text/css"
  media="all"
  />
  <!-- reponsive -->
  <script
  type="text/javascript"
  src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js?ver=3.2.1"
  ></script>
</head>
<body
style="background-color: #98c5e9"
class="page-template page-template-page-templates page-template-company page-template-page-templatescompany-php page page-id-53 offcanvas"
data-gr-c-s-loaded="true"
>
<div class="off-canvas-wrapper">
  <div
  class="off-canvas position-left is-transition-push is-closed"
  id="offCanvas"
  data-off-canvas=""
  aria-hidden="true"
  data-e="kqk5b8-e"
  >
  <div class="mobile-main-menu">
    <ul
    id="menu-main-menu"
    class="vertical menu"
    data-accordion-menu=""
    data-submenu-toggle="true"
    role="tree"
    aria-multiselectable="true"
    data-e="l5xezs-e"
    >
    <li
    id="menu-item-55"
    class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-53 current_page_item menu-item-55 is-active"
    role="treeitem"
    aria-hidden="false"
    >
    <a href="{% url 'mcfcapp:clienthome' %}">Home</a>
  </li>
  <li
  id="menu-item-119"
  class="menu-item menu-item-type-post_type menu-item-object-page menu-item-119"
  role="treeitem"
  >
  <a href="{% url 'mcfcapp:clientmember' %}">Members</a>
</li>
<li
id="menu-item-182"
class="menu-item menu-item-type-post_type menu-item-object-page menu-item-182"
role="treeitem"
>
<a href="#">Events</a>
</li>
<li
id="menu-item-1005"
class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1005"
role="treeitem"
>
<a href="#">WallPaper Gallery</a>
</li>
<li
id="menu-item-682"
class="login menu-item menu-item-type-custom menu-item-object-custom menu-item-682"
role="treeitem"
>
<a href="#" data-open="login-modal">Merchandise Comparison</a>
</li>
</ul>
</div>
</div>
<div class="js-off-canvas-overlay is-overlay-fixed"></div>

<div class="off-canvas-content" data-off-canvas-content="">
  <header class="site-header" role="banner">
    <div id="main-header" class="grid-container">
      <button
      class="hamburger hamburger--spin"
      type="button"
      data-toggle="offCanvas"
      aria-expanded="false"
      aria-controls="offCanvas"
      >
      <span class="hamburger-box">
        <span class="hamburger-inner"></span>
      </span>
    </button>

    <a id="logo-link" href="#" rel="Home">
      <img id="logo" src="{% static 'clientstatic/homepage/image/logo.png' %}" alt="Place your logo" />
    </a>

    <a id="mobile-call" href="tel:+9779882828282"
    ><i class="fa fa-phone" aria-hidden="true"></i
      ></a>

      <nav>
        <!--  -->
        <div class="menu-main-menu-container">
          <ul id="menu-main-menu-1" class="menu">
            <li
            class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-53 current_page_item menu-item-55 is-active"
            >
            <a href="{% url 'mcfcapp:clienthome' %}">Home</a>
          </li>
          <li
          class="menu-item menu-item-type-post_type menu-item-object-page menu-item-119"
          >
          <a href="{% url 'mcfcapp:clientmember' %}">Members</a>
        </li>
        <li
        class="menu-item menu-item-type-post_type menu-item-object-page menu-item-182"
        >
        <a href="{% url 'mcfcapp:clientevent' %}">Events</a>
      </li>
      <li
      class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1005"
      >
      <a href="{% url 'mcfcapp:clientgallery' %}">WallPaper Gallery</a>
    </li>
    <li
    class="menu-item menu-item-type-post_type menu-item-object-page menu-item-413"
    >
    <a href="#">Merchandise Comparison</a>
  </li>
</ul>
</div>
</nav>
</div>
</header>
{% block content %}


{% endblock %}

<div class="footer-container" data-sticky-footer="">
  <footer class="footer grid-x">
    <a id="back-top" href="#"
    ><i class="fa fa-angle-up" aria-hidden="true"></i
      ></a>
      <div class="medium-6 cell grid-x footer-menu grid-padding-x">
        <div class="medium-6 cell">

        </div>
      </div>
      <div class="medium-6 cell" style="color: white;">   <br /></div>
    </footer>
    <div class="copyright-holder">
      <div class="grid-container">
        © Copyright MCSCN 2019
      </div>
    </div>
  </div>

  <!-- Login Modal -->

  <!-- Signup Modal -->

  <script
  type="text/javascript"
  src="https://websitetravel.com/wp-content/plugins/easy-load-more/assets/js/frontend.min.js?ver=1.0.0"
  ></script>
  <script
  type="text/javascript"
  src="https://websitetravel.com/wp-content/themes/websitetravel/dist/assets/js/app.js?ver=2.10.3"
  ></script>
  <script
  type="text/javascript"
  src="https://websitetravel.com/wp-includes/js/wp-embed.min.js?ver=4.9.9"
  ></script>
  <script type="text/javascript">
    var elm_button_vars = { wrapper: "#news-post-holder" };
  </script>
</div>
<!-- Closing off-canvas-content tag-->
</div>
<div class="reveal-overlay">
  <div
  class="reveal center"
  id="login-modal"
  data-reveal=""
  role="dialog"
  aria-hidden="true"
  data-yeti-box="login-modal"
  data-resize="login-modal"
  data-e="7foepl-e"
  data-events="resize"
  style="top: 133px;"
  >
  <h3 class="large">Choose Login Area</h3>
  <div class="grid-x grid-margin-x">
    <div class="light-grey small-12 medium-6 cell login-box">
      <img
      src="https://websitetravel.com/wp-content/themes/websitetravel/dist/assets/images/products/tdms.svg"
      />
      <h4>Agent</h4>
      <a
      class="button"
      href="https://tdms.websitetravel.com/"
      target="_blank"
      title="Login to TDMS"
      >Login</a
      >
    </div>
    <div class="blue-grey small-12 medium-6 cell login-box">
      <img
      src="https://websitetravel.com/wp-content/themes/websitetravel/dist/assets/images/products/cms.svg"
      />
      <h4>Operator / Supplier</h4>
      <a
      class="button"
      href="https://cms.websitetravel.com/"
      target="_blank"
      title="Login to CMS"
      >Login</a
      >
    </div>
  </div>

  <button
  class="close-button"
  data-close=""
  aria-label="Close modal"
  type="button"
  >
  <i class="fa fa-times-circle" aria-hidden="true"></i>
</button>
</div>
</div>
<div class="reveal-overlay">
  <div
  class="reveal center"
  id="signup-modal"
  data-reveal=""
  role="dialog"
  aria-hidden="true"
  data-yeti-box="signup-modal"
  data-resize="signup-modal"
  data-e="zdvcbp-e"
  data-events="resize"
  style="top: 133px;"
  >
  <h3 class="large">Sign Up</h3>
  <div class="grid-x grid-margin-x">
    <div class="light-grey small-12 medium-6 cell login-box">
      <img
      src="https://websitetravel.com/wp-content/themes/websitetravel/dist/assets/images/agents.svg"
      />
      <h4>Agent</h4>
      <a class="button" href="#" title="Login to TDMS"></a>
    </div>
    <div class="blue-grey small-12 medium-6 cell login-box">
      <img
      src="https://websitetravel.com/wp-content/themes/websitetravel/dist/assets/images/suppliers.svg"
      />
      <h4>Operator / Supplier</h4>
      <a class="button" href="#" title="Login to CMS"></a>
    </div>
  </div>

  <button
  class="close-button"
  data-close=""
  aria-label="Close modal"
  type="button"
  >
  <i class="fa fa-times-circle" aria-hidden="true"></i>
</button>
</div>
</div>
<!-- Closing Off canvas wrapper tag -->
</body>
</html>

templates/clienttemplates/clienteventpage.html
{% extends 'clienttemplates/clientbasepage.html' %}

{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Design</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'clientstatic/event/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'clientstatic/event/css/fonts.css' %}"/>
    <link rel="stylesheet" href="{% static 'clientstatic/event/css/style.css' %}">
</head>
<!--This is where the header starts-->
<div class="jumbotron jumbo1">
    <h1>New Event Orgnized</h1>
    <p>24 Jan 2019, 10:30 AM</p>
    <div class="social-links">
        <a href="#"><i class="fa fa-google-plus fa-lg"></i></a>
        <a href="#"><i class="fa fa-pinterest fa-lg"></i></a>
        <a href="#"><i class="fa fa-twitter fa-lg"></i></a>
        <a href="#"><i class="fa fa-facebook fa-lg"></i></a>
    </div>
</div>
<!--This is where the header ends-->

<div class="container blog">



    <!--Blog Section-->
    <div class="m-5 row ">
        <div class="col-sm-8" style="border: solid">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
            </p>
            <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
            </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
            </p>
            <p>
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
            </p>
            <div class="jumbotron c_jumbotron"><p>Ad Here</p></div>
            <h3>Main Highlights</h3>
            <p>
                <img src="{% static 'clientstatic/event/images/cover.jpg' %}" class="img-thumbnail thumbnail">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
                Lorem ipsum dolor sit amet, consectetur adipisicing elit...
            </p>
            <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...
            </p>
            <div class="jumbotron c_jumbotron"><p>Ad Here</p></div>


        </div>

        <div class="col-sm-4">
            <aside>
                <h3>Other Blogs</h3>
                <div class="sponsorBlog">
                    <div class="thumb_sponsor">
                        <section>
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="#" class="float-right">
                                        <h4 class="heading_sponsor">City Won The League</h4>
                                    </a>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>

                <div class="sponsorBlog">
                    <div class="thumb_sponsor">
                        <section>
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="#" class="float-right">
                                        <h4 class="heading_sponsor">City Won The League</h4>
                                    </a>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>

                <div class="sponsorBlog">
                    <div class="thumb_sponsor">
                        <section>
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="#" class="float-right">
                                        <h4 class="heading_sponsor">City Won The League</h4>
                                    </a>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
			
            </aside>

            
        </div>
    </div>
    <!--END is blog Section-->

    <!--Comment Form-->


        <!--Google auto ad section-->
        <!--ends google auto ad-->
    </div>
</div>

<footer class="footer"><span class="footer_text">Copy right 2019</span></footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</body>
</html>
{% endblock %}

templates/clienttemplates/clientgallerypage.html
{% extends 'clienttemplates/clientbasepage.html' %}

{% load static %}


{% block content %}

 <h2>Responsive Image Gallery</h2>
    <h4>Resize the browser window to see the effect.</h4>

    <div class="responsive">
      <div class="gallery">
        <a target="_blank" href="{%static 'clientstatic/gallery/image/Celeb.jpg' %}">
          <img
            src="{%static 'clientstatic/gallery/image/Celeb.jpg' %}"
            alt="Cinque Terre"
            width="600"
            height="400"
          />
        </a>
        <div class="desc">Add a description of the image here</div>
      </div>
    </div>

    <div class="responsive">
      <div class="gallery">
        <a target="_blank" href="{%static 'clientstatic/gallery/image/Kdv.jpg' %}">
          <img src="./image/Kdv.jpg" alt="Forest" width="600" height="400" />
        </a>
        <div class="desc">Add a description of the image here</div>
      </div>
    </div>

    <div class="responsive">
      <div class="gallery">
        <a target="_blank" href="{%static 'clientstatic/gallery//image/PEP.jpg' %}">
          <img
            src="./image/PEP.jpg"
            alt="Northern Lights"
            width="600"
            height="400"
          />
        </a>
        <div class="desc">Add a description of the image here</div>
      </div>
    </div>



    <div class="clearfix"></div>

    <div style="padding:6px;">
      <p>
        This example use media queries to re-arrange the images on different
        screen sizes: for screens larger than 700px wide, it will show four
        images side by side, for screens smaller than 700px, it will show two
        images side by side. For screens smaller than 500px, the images will
        stack vertically (100%).
      </p>
      <p>
        You will learn more about media queries and responsive web design later
        in our CSS Tutorial.
      </p>
    </div>
  </body>
</html>

{% endblock %}

templates/clienttemplates/clienthomepage.html
{% extends 'clienttemplates/clientbasepage.html' %}

{% load static %}

{% block content %}
<section class="container">
  <div class="for-seo">
    <!-- <h1 class="entry-title">Company Profile</h1> -->
  </div>

  <div id="internal-banner">
    <img
    id="desktop-hero"
    src="{% static 'clientstatic/homepage/image/cover.jpg' %}"
    style="width: inherit; height: inherit"
    />
    <!-- <img id="mobile-hero" src=""> -->

    <div
    class="grid-x grid-container grid-padding-x align-right align-middle leadspace-text"
    >
    <div class="large-5 cell">
      <!-- Repeater fields for CTA -->
    </div>
  </div>
</div>

<div id="stats">
  <div
  class="grid-x align-spaced brands grid-padding-x grid-container"
  >
  <div class="stat-list small-12 medium-2 large-2 cell">
    <img src="{% static 'clientstatic/homepage/image/members.png' %}" alt="Members" />
    <div class="stat-numbers">
      <div class="numbers">800</div>
      <div class="stat-label">Total Members</div>
    </div>
  </div>
  <div class="stat-list small-12 medium-2 large-2 cell">
    <img src="{% static 'clientstatic/homepage/image/patners.png' %}" alt="Patners" />
    <div class="stat-numbers">
      <div class="numbers">200</div>
      <div class="stat-label">International members</div>
    </div>
  </div>
  <div class="stat-list small-12 medium-2 large-2 cell">
    <img src="{% static 'clientstatic/homepage/image/international.png' %}" alt="international" />
    <div class="stat-numbers">
      <div class="numbers">600</div>
      <div class="stat-label">International Member</div>
    </div>
  </div>
  <div class="stat-list small-12 medium-2 large-2 cell">
    <img src="{% static 'clientstatic/homepage/image/executives.png' %}" alt="Executives" />
    <div class="stat-numbers">
      <div class="numbers">11</div>
      <div class="stat-label">Executatives</div>
    </div>
  </div>
</div>
</div>

<!-- Stat template part -->

<section class="center padded about-bg">
  <article class="grid-container grid-x grid-padding-x">
    <div class="small-12 cell">
      <h2>About Us</h2>
      <p class="intro-text">
        Li Europan lingues es membres del sam familie. Lor separat
        existentie es un myth. Por scientie, musica, sport etc, litot
        Europa usa li sam vocabular. Li lingues differe solmen in li
        grammatica, li pronunciation e li plu commun vocabules.
        Omnicos directe al desirabilite de un no
      </p>
      <div style="width: 100%">
        <iframe
        width="560"
        height="315"
        src="https://www.youtube.com/embed/CAUGgCVEdyk"
        frameborder="0"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
        ></iframe>
      </div>
      <br />
      <div class="main-text">
        <p>
          Li Europan lingues es membres del sam familie. Lor separat
          existentie es un myth. Por scientie, musica, sport etc,
          litot Europa usa li sam vocabular. Li lingues differe solmen
          in li grammatica, li pronunciation e li plu commun
          vocabules. Omnicos directe al desirabilite de un nov lingua
          franca: On refusa continuar payar custosi traductores. At
          solmen va esser necessi far uniform grammatica,
          pronunciation e plu sommun paroles. Ma quande lingues
          coalesce, li grammatica del resultant lingue es plu simplic
          e regulari quam ti del coalescent lingues. Li nov lingua
          franca va esser plu simplic e regulari quam li existent
          Europan lingues. It va esser tam simplic quam Occidental in
          fact, it va esser Occidental. A un Angleso it va semblar un
          simplificat Angles, quam un skeptic Cambridge amico dit me
          que Occidental es.Li Europan lingues es membres del sam
          familie. Lor separat existentie es un myth. Por scientie,
          musica, sport etc, litot Europa usa li sam vocabular. Li
          lingues differe solmen in li grammatica, li pronunciation e
          li plu commun vocabules. Omnicos directe al desirabilite de
          un nov lingua franca: On refusa continuar payar custosi
          traductores. At solmen va esser necessi far uniform
          grammatica, pronunciation e plu sommun paroles.
        </p>
        <p>
          Li Europan lingues es membres del sam familie. Lor separat
          existentie es un myth. Por scientie, musica, sport etc,
          litot Europa usa li sam vocabular. Li lingues differe solmen
          in li grammatica, li pronunciation e li plu commun
          vocabules. Omnicos directe al desirabilite de un nov lingua
          franca: On refusa continuar payar custosi traductores. At
          solmen va esser necessi far uniform grammatica,
          pronunciation e plu sommun paroles. Ma quande lingues
          coalesce, li grammatica del resultant lingue es plu simplic
          e regulari quam ti del coalescent lingues. Li nov lingua
          franca va esser plu simplic e regulari quam li existent
          Europan lingues. It va esser tam simplic quam Occidental in
          fact, it va esser Occidental. A un Angleso it va semblar un
          simplificat Angles, quam un skeptic Cambridge amico dit me
          que Occidental es.Li Europan lingues es membres del sam
          familie. Lor separat existentie es un myth. Por scientie,
          musica, sport etc, litot Europa usa li sam vocabular. Li
          lingues differe solmen in li grammatica, li pronunciation e
          li plu commun vocabules. Omnicos directe al desirabilite de
          un nov lingua franca: On refusa continuar payar custosi
          traductores. At solmen va esser necessi far uniform
          grammatica, pronunciation e plu sommun paroles.
        </p>
        <p>
          Li Europan lingues es membres del sam familie. Lor separat
          existentie es un myth. Por scientie, musica, sport etc,
          litot Europa usa li sam vocabular. Li lingues differe solmen
          in li grammatica, li pronunciation e li plu commun
          vocabules. Omnicos directe al desirabilite de un nov lingua
          franca: On refusa continuar payar custosi traductores. At
          solmen va esser necessi far uniform grammatica,
          pronunciation e plu sommun paroles. Ma quande lingues
          coalesce, li grammatica del resultant lingue es plu simplic
          e regulari quam ti del coalescent lingues. Li nov lingua
          franca va esser plu simplic e regulari quam li existent
          Europan lingues. It va esser tam simplic quam Occidental in
          fact, it va esser Occidental. A un Angleso it va semblar un
          simplificat Angles, quam un skeptic Cambridge amico dit me
          que Occidental es.Li Europan lingues es membres del sam
          familie. Lor separat existentie es un myth. Por scientie,
          musica, sport etc, litot Europa usa li sam vocabular. Li
          lingues differe solmen in li grammatica, li pronunciation e
          li plu commun vocabules. Omnicos directe al desirabilite de
          un nov lingua franca: On refusa continuar payar custosi
          traductores. At solmen va esser necessi far uniform
          grammatica, pronunciation e plu sommun paroles.
        </p>
        <p>
          Li Europan lingues es membres del sam familie. Lor separat
          existentie es un myth. Por scientie, musica, sport etc,
          litot Europa usa li sam vocabular. Li lingues differe solmen
          in li grammatica, li pronunciation e li plu commun
          vocabules. Omnicos directe al desirabilite de un nov lingua
          franca: On refusa continuar payar custosi traductores. At
          solmen va esser necessi far uniform grammatica,
          pronunciation e plu sommun paroles. Ma quande lingues
          coalesce, li grammatica del resultant lingue es plu simplic
          e regulari quam ti del coalescent lingues. Li nov lingua
          franca va esser plu simplic e regulari quam li existent
          Europan lingues. It va esser tam simplic quam Occidental in
          fact, it va esser Occidental. A un Angleso it va semblar un
          simplificat Angles, quam un skeptic Cambridge amico dit me
          que Occidental es.Li Europan lingues es membres del sam
          familie. Lor separat existentie es un myth. Por scientie,
          musica, sport etc, litot Europa usa li sam vocabular. Li
          lingues differe solmen in li grammatica, li pronunciation e
          li plu commun vocabules. Omnicos directe al desirabilite de
          un nov lingua franca: On refusa continuar payar custosi
          traductores. At solmen va esser necessi far uniform
          grammatica, pronunciation e plu sommun paroles.
        </p>
      </div>
    </div>
  </article>
</section>

<!-- Team Members -->
<section class="center padded light-grey">
  <article>
    <h2>Some Of Our Team Members</h2>
    <div
    class="grid-container grid-x grid-container-padded team-members"
    >
    <div
    class="medium-6 large-3 cell grid-x team align-self-top grid-padding-x"
    >
    <div class="small-4 medium-12 cell">
      <img src="{% static 'clientstatic/homepage/image/propic.png' %}" alt="Team" />
    </div>
    <div class="small-8 medium-12 cell align-self-top">
      <span class="name">Sijan Augero</span>
      <span class="position">Group General Manager</span>

      <a class="email-link" href="#"
      ><i class="fa fa-envelope-o" aria-hidden="true"></i>
      dummy@MCFC.com</a
      >
    </div>
  </div>
  <div
  class="medium-6 large-3 cell grid-x team align-self-top grid-padding-x"
  >
  <div class="small-4 medium-12 cell">
    <img src="{% static 'clientstatic/homepage/image/propic.png' %}" alt="Team" />
  </div>
  <div class="small-8 medium-12 cell align-self-top">
    <span class="name">Sane babu</span>
    <span class="position">Player </span>

    <a class="email-link" href="#"
    ><i class="fa fa-envelope-o" aria-hidden="true"></i>
    dummy@MCFC.com</a
    >
  </div>
</div>
<div
class="medium-6 large-3 cell grid-x team align-self-top grid-padding-x"
>
<div class="small-4 medium-12 cell">
  <img src="{% static 'clientstatic/homepage/image/propic.png' %}" alt="Team" />
</div>
<div class="small-8 medium-12 cell align-self-top">
  <span class="name">Kelvin Bhai</span>
  <span class="position">Passer</span>

  <a class="email-link" href="#"
  ><i class="fa fa-envelope-o" aria-hidden="true"></i>
  dummy@MCFC.com</a
  >
</div>
</div>
<div
class="medium-6 large-3 cell grid-x team align-self-top grid-padding-x"
>
<div class="small-4 medium-12 cell">
  <img src="{% static 'clientstatic/homepage/image/propic.png' %}" alt="Team" />
</div>
<div class="small-8 medium-12 cell align-self-top">
  <span class="name">PEP chora</span>
  <span class="position">Bencher</span>

  <a class="email-link" href="#"
  ><i class="fa fa-envelope-o" aria-hidden="true"></i>
  dummy@MCFC.com</a
  >
</div>
</div>
</div>
</article>
</section>
</section>
{% endblock %}

templates/clienttemplates/clientmemberpage.html
{% extends 'clienttemplates/clientbasepage.html' %}

{% load static %}

{% block content %}
<section class="container">
	<div class="for-seo">
		<!-- <h1 class="entry-title">Company Profile</h1> -->
	</div>
	<h3>Fill The form for merchandise comparision</h3>
	<form action="">
		<label for="fname">First Name</label>
		<input
		type="text"
		id="fname"
		name="firstname"
		placeholder="Your name.."
		/>

		<label for="DOB">DOB</label>
		<input type="date" id="DOB" name="DOB" placeholder="Your DOB" />

		<label for="address">Address</label>
		<input
		type="text"
		id="address"
		name="address"
		placeholder="Your address.."
		/>

		<label for="email">E-mail</label>
		<input
		type="email"
		id="email"
		name="email"
		placeholder="Your email.."
		/>

		<label for="phone">Contact-no.</label>
		<input
		type="number"
		id="phone"
		name="phone"
		placeholder="Your phone number.."
		/>

		<input type="submit" value="Submit" />
	</form>
</section>



{% endblock %}